### ISSUE TITLE
Cannot connect from outside the container

### ISSUE THREAD

**Issue by jakemarchant** [nimmis/docker-apache-php7#1]
This might just be me... But I can't connect from outside the container.

I ran the container using the example run command you have.
I confirmed apache was running within the container
I confirmed my IP address is correct
I confirmed the ports had been assigned (8080 on the container and 80 on the host)

I then went onto chrome http://myipaddress:80
All I get is the connection refused, this site cannot be reached error.

This might just be me being stupid but any help would be appreciated.

**Comment by nimmis** [comment]
I think you mixed the internal and external port order. The parameter is **-p &lt;external port&gt;:&lt;local port&gt;**, apache in the container is listening on port 80 locally.

If you want to access the container on external port 80 you should start it as
**docker run -d -p 80:80 nimmis/apache-php7**

**Comment by nimmis** [comment]
I am rewriting documentation for all containers and this is a very short description, I will make it more descriptive.

**Comment by jakemarchant** [comment]
Ah, so I did... 

I was also using my local IP oppsed to my docker-machine IP which probably didn't help either. 

Thank you for your help!
