### ISSUE TITLE
custom php.ini

### ISSUE THREAD

**Issue by Judhianto** [nimmis/docker-apache-php7#6]
how to make modification in php.ini ?

**Comment by dnsene** [comment]
FROM nimmis/apache-php7
COPY ./conf/php.ini /etc/php/7.0/apache2/

**Comment by JankesJanco** [comment]
you dont have to overwrite original `php.ini` in location `/etc/php/7.0/apache2/`. Just copy `php-custom.ini` to `/etc/php/7.0/apache2/conf.d/` which will overwrite settings from `php.ini`. so the docker file will look like

```
FROM nimmis/apache-php7

COPY ./conf/php-custom.ini /etc/php/7.0/apache2/conf.d/php-custom.ini
```

Note: the name of the custom config file does not have to be `php-custom.ini`. Every *.ini file from `conf.d` directory will be loaded by php. look [here](https://askubuntu.com/a/1000109)

**Comment by Judhianto** [comment]
Thank you
